create table quizquestion (
	id INT,
	quizId INT,
	question TEXT,
	quesDesc TEXT,
	answer INT,
	opt1 TEXT,
	opt1Img VARCHAR(50),
	opt2 TEXT,
	opt2Img VARCHAR(50),
	opt3 TEXT,
	opt3Img VARCHAR(50),
	opt4 TEXT,
	opt4Img VARCHAR(50),
	score INT
);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (1, 2, 'blandit non', 'Proin at turpis a pede posuere nonummy.', 2, 'blandit nam nulla', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 'donec quis', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'amet', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'venenatis turpis enim blandit mi', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (2, 3, 'mattis pulvinar', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 1, 'mauris sit amet', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'ut dolor', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'blandit nam nulla integer', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'lacus purus aliquet at feugiat', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (3, 3, 'ac nibh', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 2, 'id ligula', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'posuere', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'eu pede', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'integer aliquet massa', 'http://dummyimage.com/100x100.png/dddddd/000000', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (4, 3, 'praesent id', 'Curabitur convallis.', 4, 'est risus', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'eget nunc', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 'vivamus', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'posuere', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (5, 1, 'sit amet', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 3, 'tristique est et tempus', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 'vestibulum ante ipsum', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'sapien quis', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'nascetur ridiculus mus etiam vel', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (6, 1, 'augue vestibulum', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 1, 'interdum venenatis turpis enim', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'sapien dignissim vestibulum vestibulum ante', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'semper porta volutpat quam pede', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'massa id nisl', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (7, 2, 'primis in faucibus', 'Integer a nibh.', 4, 'sed vel enim sit', 'http://dummyimage.com/100x100.png/dddddd/000000', 'lobortis vel', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'luctus et ultrices posuere', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'convallis', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (8, 2, 'eget vulputate ut', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 3, 'libero', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'sagittis', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'ridiculus mus', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'vel lectus in quam', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (9, 2, 'pede', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 1, 'cras mi pede', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'vulputate ut ultrices vel augue', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 'curabitur in libero', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 'luctus cum sociis natoque', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (10, 3, 'blandit non', 'Aliquam quis turpis eget elit sodales scelerisque.', 3, 'orci nullam', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'aliquam convallis nunc proin at', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'at nibh in hac habitasse', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 'aenean', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (11, 3, 'id massa', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 3, 'nunc rhoncus dui vel sem', 'http://dummyimage.com/100x100.png/dddddd/000000', 'eget massa tempor convallis', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'sodales', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 'nulla pede ullamcorper augue', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (12, 3, 'ultrices', 'Nam nulla.', 3, 'ante vivamus tortor duis', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'eros viverra', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'primis in', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'vitae mattis nibh ligula', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (13, 3, 'ut rhoncus', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 2, 'eu sapien cursus vestibulum', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'morbi porttitor', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'primis in faucibus', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 'odio curabitur convallis duis consequat', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (14, 1, 'molestie', 'Proin eu mi.', 3, 'curae duis', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'donec', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'molestie lorem', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'dui maecenas tristique', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (15, 3, 'semper porta volutpat', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 4, 'morbi quis tortor id nulla', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'sed', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'metus sapien ut', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'ut', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (16, 3, 'nisi', 'Nullam varius.', 4, 'vel accumsan tellus', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 'ac', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'nulla nunc', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'rutrum rutrum neque aenean', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (17, 1, 'tincidunt', 'Cras non velit nec nisi vulputate nonummy.', 1, 'justo pellentesque viverra', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'ipsum', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'nulla quisque arcu libero rutrum', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'nisl venenatis lacinia', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (18, 1, 'mauris', 'Quisque porta volutpat erat.', 2, 'curabitur in libero ut', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'commodo placerat praesent blandit nam', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'sagittis sapien cum sociis natoque', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 'sit amet diam', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (19, 3, 'eget eros', 'Nulla nisl. Nunc nisl.', 2, 'sollicitudin vitae', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'amet nulla quisque', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'bibendum imperdiet nullam', 'http://dummyimage.com/100x100.png/dddddd/000000', 'a odio in', 'http://dummyimage.com/100x100.png/dddddd/000000', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (20, 2, 'iaculis justo in', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 1, 'at velit eu', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'turpis sed ante vivamus', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'penatibus et', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'in est risus', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (21, 2, 'montes nascetur ridiculus', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1, 'lacinia sapien', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 'eget elit sodales', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 'etiam pretium iaculis', 'http://dummyimage.com/100x100.png/dddddd/000000', 'sagittis sapien', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (22, 3, 'rutrum', 'Proin risus. Praesent lectus.', 3, 'sed augue', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'enim leo', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'magna vulputate luctus cum sociis', 'http://dummyimage.com/100x100.png/dddddd/000000', 'donec semper sapien a libero', 'http://dummyimage.com/100x100.png/dddddd/000000', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (23, 2, 'odio donec vitae', 'Nunc rhoncus dui vel sem. Sed sagittis.', 2, 'hac habitasse platea dictumst morbi', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'maecenas ut massa', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'ac diam cras pellentesque volutpat', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'orci', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (24, 2, 'platea dictumst', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 2, 'interdum', 'http://dummyimage.com/100x100.png/dddddd/000000', 'eros elementum pellentesque', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'ante ipsum', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'donec ut mauris eget massa', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (25, 2, 'massa id nisl', 'Phasellus id sapien in sapien iaculis congue.', 3, 'varius integer ac', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'donec ut mauris eget', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'vivamus vestibulum sagittis', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'pede libero quis orci', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (26, 2, 'habitasse', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 3, 'bibendum imperdiet nullam', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'odio odio elementum eu', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'posuere nonummy integer non velit', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'tellus nisi eu', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (27, 3, 'ridiculus mus', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', 3, 'quisque id justo sit amet', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'pede justo lacinia eget', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'justo in blandit ultrices enim', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'proin', 'http://dummyimage.com/100x100.png/dddddd/000000', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (28, 2, 'cursus', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 2, 'sapien sapien non', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'nisl aenean lectus', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'blandit lacinia erat', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'nibh in hac habitasse', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (29, 2, 'sem', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 4, 'felis sed lacus morbi', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'pretium iaculis diam', 'http://dummyimage.com/100x100.png/dddddd/000000', 'velit eu est', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'primis in', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (30, 1, 'suscipit', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 4, 'ultricies eu nibh quisque id', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'vestibulum ante ipsum primis in', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'massa volutpat', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'non interdum in', 'http://dummyimage.com/100x100.png/dddddd/000000', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (31, 3, 'justo sit', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 2, 'ligula vehicula consequat', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'sit amet', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'luctus', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'nisl duis ac nibh', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (32, 1, 'elit sodales scelerisque', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 3, 'commodo', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 'ultrices posuere cubilia curae', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'pellentesque quisque', 'http://dummyimage.com/100x100.png/dddddd/000000', 'nisl duis ac nibh', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (33, 3, 'eget orci', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 2, 'velit donec diam neque', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'pulvinar lobortis est phasellus', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'ipsum primis in faucibus orci', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'luctus nec molestie', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (34, 2, 'dui vel nisl', 'Phasellus in felis.', 3, 'ac diam cras pellentesque', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'cubilia curae duis faucibus', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 'eget vulputate', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 'massa id nisl venenatis lacinia', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (35, 2, 'nulla ultrices aliquet', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3, 'hendrerit at vulputate vitae nisl', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'purus', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'in faucibus orci luctus et', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'in libero ut', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (36, 3, 'amet consectetuer', 'Duis ac nibh.', 4, 'vitae ipsum aliquam non mauris', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 'porttitor pede justo eu', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'cursus id turpis integer', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 'donec quis', 'http://dummyimage.com/100x100.png/dddddd/000000', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (37, 3, 'massa', 'Integer a nibh. In quis justo.', 3, 'libero nam dui proin leo', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'id turpis integer', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 'pretium', 'http://dummyimage.com/100x100.png/dddddd/000000', 'libero quis orci nullam molestie', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (38, 3, 'vestibulum rutrum rutrum', 'Nulla mollis molestie lorem. Quisque ut erat.', 2, 'eu tincidunt in leo maecenas', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'tortor quis turpis sed ante', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'id sapien in', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'erat eros viverra eget', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 2);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (39, 1, 'elementum nullam', 'Proin eu mi.', 2, 'porta volutpat erat quisque', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'vehicula', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'est donec', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'nulla', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (40, 3, 'vestibulum eget vulputate', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 3, 'erat', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'metus arcu adipiscing', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'massa id', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'amet sem fusce consequat nulla', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (41, 3, 'morbi', 'Sed sagittis.', 1, 'imperdiet et', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'vehicula consequat morbi a', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 'justo pellentesque', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'eleifend pede libero quis orci', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (42, 3, 'diam', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 3, 'vestibulum proin eu mi', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 'vulputate elementum', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 'imperdiet nullam orci pede venenatis', 'http://dummyimage.com/100x100.png/cc0000/ffffff', 'vehicula condimentum curabitur', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (43, 2, 'ligula', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 3, 'tincidunt eget tempus vel', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'volutpat in', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'lectus aliquam sit', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'sem mauris laoreet', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (44, 3, 'lorem', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 3, 'duis', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'nec sem duis aliquam', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'condimentum neque sapien placerat ante', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'morbi non', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (45, 1, 'ut nunc', 'Curabitur at ipsum ac tellus semper interdum.', 3, 'nulla facilisi cras', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'magnis dis parturient montes', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'sit amet justo morbi ut', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 'volutpat sapien arcu sed augue', 'http://dummyimage.com/100x100.png/dddddd/000000', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (46, 3, 'non mauris morbi', 'Nulla mollis molestie lorem. Quisque ut erat.', 3, 'in', 'http://dummyimage.com/100x100.bmp/cc0000/ffffff', 'pede libero quis', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'convallis', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', 'nec molestie', 'http://dummyimage.com/100x100.png/dddddd/000000', 3);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (47, 1, 'ac enim in', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 2, 'proin eu mi nulla', 'http://dummyimage.com/100x100.jpg/dddddd/000000', 'vulputate justo in blandit ultrices', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'ultricies', 'http://dummyimage.com/100x100.png/dddddd/000000', 'augue luctus tincidunt nulla', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (48, 2, 'consequat dui nec', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 3, 'erat curabitur gravida nisi', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'sit amet nunc viverra', 'http://dummyimage.com/100x100.png/dddddd/000000', 'nisi volutpat eleifend donec ut', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 'dignissim', 'http://dummyimage.com/100x100.bmp/dddddd/000000', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (49, 1, 'maecenas', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, 'volutpat sapien', 'http://dummyimage.com/100x100.png/dddddd/000000', 'augue aliquam erat volutpat in', 'http://dummyimage.com/100x100.bmp/ff4444/ffffff', 'turpis nec euismod scelerisque quam', 'http://dummyimage.com/100x100.jpg/ff4444/ffffff', 'donec', 'http://dummyimage.com/100x100.bmp/5fa2dd/ffffff', 1);
insert into quizquestion (id, quizId, question, quesDesc, answer, opt1, opt1Img, opt2, opt2Img, opt3, opt3Img, opt4, opt4Img, score) values (50, 2, 'lectus aliquam sit', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 1, 'pellentesque at nulla suspendisse potenti', 'http://dummyimage.com/100x100.jpg/cc0000/ffffff', 'suscipit ligula in', 'http://dummyimage.com/100x100.png/ff4444/ffffff', 'mauris', 'http://dummyimage.com/100x100.png/dddddd/000000', 'sodales sed tincidunt', 'http://dummyimage.com/100x100.jpg/5fa2dd/ffffff', 3);
